
spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    time-to-live: 60000
    cache-null-values: true


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rediscachepractice?useSSL=false
    username: root
    password: password
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: